// eslint-disable-next-line no-shadow
export enum InjectionToken {
  USER_REPOSITORY = 'USER_REPOSITORY',
  USER_READER_USE_CASE = 'USER_READER_USE_CASE',
  USER_CREATOR_USE_CASE = 'USER_CREATOR_USE_CASE',
  USER_UPDATER_USE_CASE = 'USER_UPDATER_USE_CASE',
  USER_GAME_MANAGER_USE_CASE = 'USER_GAME_MANAGER_USE_CASE',
  USER_GACHA_MANAGER_USE_CASE = 'USER_GACHA_MANAGER_USE_CASE',
  USER_PUBLISHER_USE_CASE = 'USER_PUBLISHER_USE_CASE',

  CHARACTER_STATUS_REPOSITORY = 'CHARACTER_STATUS_REPOSITORY',

  ITEM_REPOSITORY = 'ITEM_REPOSITORY',

  ITEM_COMPLETED_HISTORY_REPOSITORY = 'ITEM_COMPLETED_HISTORY_REPOSITORY',

  GIFT_REPOSITORY = 'GIFT_REPOSITORY',
  GIFT_READER_USE_CASE = 'GIFT_READER_USE_CASE',

  GIFT_HISTORY_REPOSITORY = 'GIFT_HISTORY_REPOSITORY',
  GIFT_HISTORY_READER_USE_CASE = 'GIFT_HISTORY_READER_USE_CASE',
  GIFT_HISTORY_CREATOR_USE_CASE = 'GIFT_HISTORY_CREATOR_USE_CASE',
  GIFT_HISTORY_UPDATER_USE_CASE = 'GIFT_HISTORY_UPDATERUSE_CASE',
}
