// eslint-disable-next-line no-shadow
export enum InjectionToken {
  GIFT = 'GIFT',
  NESTED_GIFT = 'NESTED_GIFT',
  GIFT_REPOSITORY = 'GIFT_REPOSITORY',
  GIFT_READER_USE_CASE = 'GIFT_READER_USE_CASE',

  GIFT_HISTORY = 'GIFT_HISTORY',
  NESTED_GIFT_HISTORY = 'NESTED_GIFT_HISTORY',
  GIFT_HISTORY_REPOSITORY = 'GIFT_HISTORY_REPOSITORY',
  GIFT_HISTORY_READER_USE_CASE = 'GIFT_HISTORY_READER_USE_CASE',
  GIFT_HISTORY_CREATOR_USE_CASE = 'GIFT_HISTORY_CREATOR_USE_CASE',
  GIFT_HISTORY_UPDATER_USE_CASE = 'GIFT_HISTORY_UPDATERUSE_CASE',

  ITEM = 'ITEM',
  NESTED_ITEM = 'NESTED_ITEM',
  ITEM_REPOSITORY = 'ITEM_REPOSITORY',

  USER = 'USER',
  NESTED_USER = 'NESTED_USER',
  USER_REPOSITORY = 'USER_REPOSITORY',
  USER_READER_USE_CASE = 'USER_READER_USE_CASE',
  USER_CREATOR_USE_CASE = 'USER_CREATOR_USE_CASE',
  USER_UPDATER_USE_CASE = 'USER_UPDATER_USE_CASE',
  USER_GAME_MANAGER_USE_CASE = 'USER_GAME_MANAGER_USE_CASE',
  USER_GACHA_MANAGER_USE_CASE = 'USER_GACHA_MANAGER_USE_CASE',
}
