name: 'Publish Graph to Current'
on:
  push:
    branches:
      - main

jobs:
  publish-graph:
    name: Publish Graph
    runs-on: ubuntu-latest
    env:
      APOLLO_KEY: ${{secrets.APOLLO_KEY}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      FIREBASE_API_KEY: ${{secrets.FIREBASE_API_KEY}}
      FIREBASE_AUTH_DOMAIN: ${{secrets.FIREBASE_AUTH_DOMAIN}}
      FIREBASE_PROJECT_ID: ${{secrets.FIREBASE_PROJECT_ID}}
      FIREBASE_STORAGE_BUCKET: ${{secrets.FIREBASE_STORAGE_BUCKET}}
      FIREBASE_MESSAGING_SENDER_ID: ${{secrets.FIREBASE_MESSAGING_SENDER_ID}}
      FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID}}
      FIREBASE_MEASUREMENT_ID: ${{secrets.FIREBASE_MEASUREMENT_ID}}
      FIREBASE_ADMIN_PROJECT_ID: ${{secrets.FIREBASE_ADMIN_PROJECT_ID}}
      FIREBASE_ADMIN_PRIVATE_KEY: ${{secrets.FIREBASE_ADMIN_PRIVATE_KEY}}
      FIREBASE_ADMIN_CLIENT_EMAIL: ${{secrets.FIREBASE_ADMIN_CLIENT_EMAIL}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Generate Prisma
        run: yarn prisma:gen:dev

      - name: Generate GraphQL Schema
        run: timeout 90 yarn dev
        continue-on-error: true

      - name: Publish Graph
        run: yarn apollo:rover
